export const ADD_MEAL = "ADD_MEAL";
export const ADD_MEAL_START = "ADD_MEAL_START";
export const ADD_MEAL_FAILED = "ADD_MEAL_FAILED";
export const ADD_MEAL_SUCCESS = "ADD_MEAL_SUCCESS";

export const ADD_MEAL_LOCAL = "ADD_MEAL_LOCAL";

export const REMOVE_MEAL = "REMOVE_MEAL";
export const REMOVE_MEAL_START = "REMOVE_MEAL_START";
export const REMOVE_MEAL_FAILED = "REMOVE_MEAL_FAILED";
export const REMOVE_MEAL_SUCCESS = "REMOVE_MEAL_SUCCESS";

export const REMOVE_MEAL_LOCAL = "REMOVE_MEAL_LOCAL";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const ADD_INGREDIENT_START = "ADD_INGREDIENT_START";
export const ADD_INGREDIENT_FAILED = "ADD_INGREDIENT_FAILED";
export const ADD_INGREDIENT_SUCCESS = "ADD_INGREDIENT_SUCCESS";

export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const UPDATE_INGREDIENT_START = "UPDATE_INGREDIENT_START";
export const UPDATE_INGREDIENT_FAILED = "UPDATE_INGREDIENT_FAILED";
export const UPDATE_INGREDIENT_SUCCESS = "UPDATE_INGREDIENT_SUCCESS";

export const ADD_INGREDIENT_LOCAL = "ADD_INGREDIENT_LOCAL";

export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const REMOVE_INGREDIENT_START = "REMOVE_INGREDIENT_START";
export const REMOVE_INGREDIENT_FAILED = "REMOVE_INGREDIENT_FAILED";
export const REMOVE_INGREDIENT_SUCCESS = "REMOVE_INGREDIENT_SUCCESS";

export const REMOVE_INGREDIENT_LOCAL = "REMOVE_INGREDIENT_LOCAL";

export const SELECT_MEAL = "SELECT_MEAL";
export const DESELECT_MEAL = "DESELECT_MEAL";

export const ADD_ITEM = "ADD_ITEM";

export const SET_MEALS = "SET_MEALS";

export const FETCH_MEALS_START = "FETCH_MEALS_START";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_FAILED = "FETCH_MEALS_FAILED";
export const FETCH_MEALS = "FETCH_MEALS";

export const FETCH_MEALS_LOCAL = "FETCH_MEALS_LOCAL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_SET_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
